//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TwitterRecord
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public string SourceScript { get; set; }
        public Nullable<System.DateTime> TweetCreationTime { get; set; }
        public string TweetLocation { get; set; }
        public string TweetHashTags { get; set; }
        public string TweetText { get; set; }
        public string InReplyToScreenName { get; set; }
        public string TweetHTML { get; set; }
        public string TweetId { get; set; }
        public string TweetURL { get; set; }
        public string TweetLanguage { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsGEOEnabled { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string Language { get; set; }
        public string ProfileBannerURL { get; set; }
        public string ProfileImageURL { get; set; }
        public string ProfileURL { get; set; }
        public string ProfileLocation { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> TotalFollowers { get; set; }
        public Nullable<int> TotalFollowing { get; set; }
        public Nullable<int> StatusCount { get; set; }
        public Nullable<int> ListedCount { get; set; }
        public string Sentiment { get; set; }
        public Nullable<System.DateTime> InsertionDateTime { get; set; }
        public int TopicID { get; set; }

        [NotMapped]
        public string TopicName { get; set; }
    }
}
